name: My GitHub Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - '*'


jobs:
  check-kvm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: ThinkParQ/checkout-action@v1
        with:
          fetch-depth: 0
      - name: Check qemu-kvm
        run: |
          n=0
          until [ "$n" -ge 5 ]; do
            success=1
            sudo apt update && sudo apt install -y cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager libvirt-daemon && break || success=0
            n=$((n+1)) 
            sleep 1
          done
          [ $success -eq 1 ] || exit 42
          sudo kvm-ok
          sudo systemctl enable --now libvirtd
          grep -E --color '(vmx|svm)' /proc/cpuinfo
