name: ON TAG PUSH

on:
  push:
    tags:
      - '*'

permissions:
  # Required to publish releases.
  contents: write

jobs:
  check-kvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: ThinkParQ/checkout-action@v1
        with:
          fetch-depth: 0
      - name: create files with names
        run: |
          echo 'tilde' > has~tilde.txt
          echo 'dash' > has-dash.txt
          echo 'space' > 'has space.txt'
          ls -ltrha
          pwd
          mkdir packages
          mv has* packages
          zip -r packages.zip packkages
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/has*"
          allowUpdates: true
          updateOnlyUnreleased: true
          removeArtifacts: true
          generateReleaseNotes: true
          draft: false
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages.zip"
          allowUpdates: true
          updateOnlyUnreleased: false
          removeArtifacts: false
          generateReleaseNotes: false
          draft: false
  