name: My GitHub Workflow

on:
  workflow_dispatch:
  push:


jobs:
  job1:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job 1
        run: |
          echo "Running Job 1"

  job2:
    if: github.event_name == 'push'
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job 2
        run: |
          echo "Running Job 2"


  manual_job:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Manual Job
        run: |
          echo "Running Job 3"
