name: Push workflow

on:
  workflow_dispatch:

jobs:
  check-kvm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: ThinkParQ/checkout-action@v1
      - name: env
        run: echo "TEST_VM_IPS=(192.168.121.36 192.168.121.243 192.168.121.157)" > .env
      - name: Check qemu-kvm
        id: hosts
        run: >
          source .env &&
          echo ${TEST_VM_IPS[@]}
          
          
          
