name: Push workflow

on:
  push:

jobs:
  check-kvm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: ThinkParQ/checkout-action@v1
      - name: Check qemu-kvm
        id: hosts
        run: |
          export TEST_VM_IPS=(192.168.121.36 192.168.121.243 192.168.121.157)
          echo "${TEST_VM_IPS[@]}" >> "$GITHUB_OUTPUT"
      - name: check array variable
        run: >
          echo ${{ steps.hosts.outputs.TEST_VM_IPS[@] }}
      - name: check only variable
        run: >
          echo ${{ steps.hosts.outputs.TEST_VM_IPS }}
          
          
